name: Build and Upload to GCS

on: workflow_dispatch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: |
          mkdir dist
          echo "Hello from GCP Bucket" > dist/output.txt

      # Authenticate with GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Install gcloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Upload to bucket
      - name: Upload to GCS
        run: |
          gsutil cp -r dist/* gs://artefact-bucket-ex/builds/${{ github.run_id }}/
