name: CI

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ModelCleaning # Applies to ALL run steps in this job
        # All commands below run inside this folder


    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Python setup 3.12
        uses: actions/setup-python@v5 
        with:
          python-version: '3.12'

      - name: Clean data  
        run: |
          pip install pandas
          python cleandata.py

      - name: Train and test model
        run: |
          pip install pandas scikit-learn
          python train_test_dataset.py
