name: CI

on:
  workflow_dispatch


jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
      - name: python setup 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: checkout code
        uses: actions/checkout@v6

      - name: clean data
        run: |
          pwd
          ls -a
          pwd
          cd ModelCleaning
          pip install pandas
          python cleandata.py

      - name: train and test model
        run: |
          pwd
          ls -a
          pwd
          cd ModelCleaning
          pip install pandas
          pip install scikit-learn
          python train_test_dataset.py